{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-08-05 09:23:31,194+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"Invalid header value b'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiZDoxIiwiZDoyIiwieDowIiwieDoxIiwieDoyIl0sImF0X2hhc2giOiJnQUFBQUFCb2tZYTI2MkdPWEs0eXpqYloyLTlkb2FwazZBVk9BWTg1M0t3anVCN2N6SzdJYmFyakVXX01ad1M1MGxqVUVwRVpCcUZjNk1laVc4WEFIdFFMM2NKM1YteXcwWnJfSlIxekFKOVhZM2dnMUV1M05OND0iLCJkaXNwbGF5X25hbWUiOiIiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiI1ZWUxMmUxN2I3NzExMGQ2MmZjZTZlNGU3YTA3YjFjMzU1MGNmNTYyMjZiMDZkYzU2NjUwYTE2ZCIsImlzRGRwaUVuYWJsZWQiOiJOIiwiaXNNdGZFbmFibGVkIjoiTiIsImZ5X2lkIjoiWFIwNDc1MCIsImFwcFR5cGUiOjEwMCwiZXhwIjoxNzU0NDQwMjAwLCJpYXQiOjE3NTQzNjc2NzAsImlzcyI6ImFwaS5meWVycy5pbiIsIm5iZiI6MTc1NDM2NzY3MCwic3ViIjoiYWNjZXNzX3Rva2VuIn0.R81zSKEwamwju6J8vBSnrjASRDY1RpAiUDQeT8BQzh4\\n'","timestamp":"2025-08-05 10:12:16,857+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 63, in symbol_to_hsmtoken\n    response = requests.post(\n               ^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\adapters.py\", line 486, in send\n    resp = conn.urlopen(\n           ^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    response = self._make_request(\n               ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 493, in _make_request\n    conn.request(\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connection.py\", line 493, in request\n    self.putheader(header, value)\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connection.py\", line 407, in putheader\n    super().putheader(header, *values)\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\http\\client.py\", line 1297, in putheader\n    raise ValueError('Invalid header value %r' % (values[i],))\nValueError: Invalid header value b'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiZDoxIiwiZDoyIiwieDowIiwieDoxIiwieDoyIl0sImF0X2hhc2giOiJnQUFBQUFCb2tZYTI2MkdPWEs0eXpqYloyLTlkb2FwazZBVk9BWTg1M0t3anVCN2N6SzdJYmFyakVXX01ad1M1MGxqVUVwRVpCcUZjNk1laVc4WEFIdFFMM2NKM1YteXcwWnJfSlIxekFKOVhZM2dnMUV1M05OND0iLCJkaXNwbGF5X25hbWUiOiIiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiI1ZWUxMmUxN2I3NzExMGQ2MmZjZTZlNGU3YTA3YjFjMzU1MGNmNTYyMjZiMDZkYzU2NjUwYTE2ZCIsImlzRGRwaUVuYWJsZWQiOiJOIiwiaXNNdGZFbmFibGVkIjoiTiIsImZ5X2lkIjoiWFIwNDc1MCIsImFwcFR5cGUiOjEwMCwiZXhwIjoxNzU0NDQwMjAwLCJpYXQiOjE3NTQzNjc2NzAsImlzcyI6ImFwaS5meWVycy5pbiIsIm5iZiI6MTc1NDM2NzY3MCwic3ViIjoiYWNjZXNzX3Rva2VuIn0.R81zSKEwamwju6J8vBSnrjASRDY1RpAiUDQeT8BQzh4\\n'","exception_name":"ValueError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-08-05 10:12:17,063+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"Invalid header value b'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiZDoxIiwiZDoyIiwieDowIiwieDoxIiwieDoyIl0sImF0X2hhc2giOiJnQUFBQUFCb2tZYTI2MkdPWEs0eXpqYloyLTlkb2FwazZBVk9BWTg1M0t3anVCN2N6SzdJYmFyakVXX01ad1M1MGxqVUVwRVpCcUZjNk1laVc4WEFIdFFMM2NKM1YteXcwWnJfSlIxekFKOVhZM2dnMUV1M05OND0iLCJkaXNwbGF5X25hbWUiOiIiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiI1ZWUxMmUxN2I3NzExMGQ2MmZjZTZlNGU3YTA3YjFjMzU1MGNmNTYyMjZiMDZkYzU2NjUwYTE2ZCIsImlzRGRwaUVuYWJsZWQiOiJOIiwiaXNNdGZFbmFibGVkIjoiTiIsImZ5X2lkIjoiWFIwNDc1MCIsImFwcFR5cGUiOjEwMCwiZXhwIjoxNzU0NDQwMjAwLCJpYXQiOjE3NTQzNjc2NzAsImlzcyI6ImFwaS5meWVycy5pbiIsIm5iZiI6MTc1NDM2NzY3MCwic3ViIjoiYWNjZXNzX3Rva2VuIn0.R81zSKEwamwju6J8vBSnrjASRDY1RpAiUDQeT8BQzh4\\n'","timestamp":"2025-08-05 20:25:36,029+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 63, in symbol_to_hsmtoken\n    response = requests.post(\n               ^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\adapters.py\", line 486, in send\n    resp = conn.urlopen(\n           ^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    response = self._make_request(\n               ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 493, in _make_request\n    conn.request(\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connection.py\", line 493, in request\n    self.putheader(header, value)\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connection.py\", line 407, in putheader\n    super().putheader(header, *values)\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\http\\client.py\", line 1297, in putheader\n    raise ValueError('Invalid header value %r' % (values[i],))\nValueError: Invalid header value b'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiZDoxIiwiZDoyIiwieDowIiwieDoxIiwieDoyIl0sImF0X2hhc2giOiJnQUFBQUFCb2tZYTI2MkdPWEs0eXpqYloyLTlkb2FwazZBVk9BWTg1M0t3anVCN2N6SzdJYmFyakVXX01ad1M1MGxqVUVwRVpCcUZjNk1laVc4WEFIdFFMM2NKM1YteXcwWnJfSlIxekFKOVhZM2dnMUV1M05OND0iLCJkaXNwbGF5X25hbWUiOiIiLCJvbXMiOiJLMSIsImhzbV9rZXkiOiI1ZWUxMmUxN2I3NzExMGQ2MmZjZTZlNGU3YTA3YjFjMzU1MGNmNTYyMjZiMDZkYzU2NjUwYTE2ZCIsImlzRGRwaUVuYWJsZWQiOiJOIiwiaXNNdGZFbmFibGVkIjoiTiIsImZ5X2lkIjoiWFIwNDc1MCIsImFwcFR5cGUiOjEwMCwiZXhwIjoxNzU0NDQwMjAwLCJpYXQiOjE3NTQzNjc2NzAsImlzcyI6ImFwaS5meWVycy5pbiIsIm5iZiI6MTc1NDM2NzY3MCwic3ViIjoiYWNjZXNzX3Rva2VuIn0.R81zSKEwamwju6J8vBSnrjASRDY1RpAiUDQeT8BQzh4\\n'","exception_name":"ValueError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-08-05 20:25:36,035+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-08-07 09:20:50,529+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-08-07 09:24:34,129+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-08-17 12:22:52,793+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-08-17 12:33:28,093+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-08-17 12:48:13,212+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"[Errno 11001] getaddrinfo failed","timestamp":"2025-08-18 09:26:56,003+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[symbol_to_hsmtoken:126] data_ws","message":"HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/symbol-token (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000219E8073710>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))","timestamp":"2025-08-18 09:26:58,001+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connection.py\", line 198, in _new_conn\n    sock = connection.create_connection(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\util\\connection.py\", line 60, in create_connection\n    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\socket.py\", line 963, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsocket.gaierror: [Errno 11001] getaddrinfo failed\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    response = self._make_request(\n               ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 488, in _make_request\n    raise new_e\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 464, in _make_request\n    self._validate_conn(conn)\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 1093, in _validate_conn\n    conn.connect()\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connection.py\", line 753, in connect\n    self.sock = sock = self._new_conn()\n                       ^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connection.py\", line 205, in _new_conn\n    raise NameResolutionError(self.host, self, e) from e\nurllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x00000219E8073710>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\adapters.py\", line 486, in send\n    resp = conn.urlopen(\n           ^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 841, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/symbol-token (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000219E8073710>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 63, in symbol_to_hsmtoken\n    response = requests.post(\n               ^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\requests\\adapters.py\", line 519, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPSConnectionPool(host='api-t1.fyers.in', port=443): Max retries exceeded with url: /data/symbol-token (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000219E8073710>: Failed to resolve 'api-t1.fyers.in' ([Errno 11001] getaddrinfo failed)\"))","exception_name":"ConnectionError"}
{"level":"ERROR","location":"[__symbol_conversion:1374] data_ws","message":"'NoneType' object is not subscriptable","timestamp":"2025-08-18 09:26:58,281+0530","service":"FyersDataSocket","exception":"Traceback (most recent call last):\n  File \"D:\\Datascience\\trading_setup\\venv\\Lib\\site-packages\\fyers_apiv3\\FyersWebsocket\\data_ws.py\", line 1333, in __symbol_conversion\n    if symbol_value[3] != \"\":\n       ~~~~~~~~~~~~^^^\nTypeError: 'NoneType' object is not subscriptable","exception_name":"TypeError"}
{"level":"ERROR","location":"[__symbol_conversion:1352] data_ws","message":{"code":-300,"message":"Please provide a valid symbol","s":"error","type":"sub","invalid_symbols":["NSE:SWANENERGY-EQ"]},"timestamp":"2025-09-09 10:33:11,201+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[__symbol_conversion:1352] data_ws","message":{"code":-300,"message":"Please provide a valid symbol","s":"error","type":"sub","invalid_symbols":["NSE:SWANENERGY-EQ"]},"timestamp":"2025-09-10 20:13:00,118+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[<lambda>:1663] data_ws","message":"Handshake status 502 Bad Gateway -+-+- {'date': 'Thu, 11 Sep 2025 02:19:22 GMT', 'content-type': 'text/plain; charset=UTF-8', 'content-length': '15', 'connection': 'keep-alive', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'referrer-policy': 'same-origin', 'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'expires': 'Thu, 01 Jan 1970 00:00:01 GMT', 'set-cookie': '_cfuvid=NlpVLyKXLXih6GJMFzT_s1Zc.0bm8fBY8wba1vNgNuA-1757557162535-0.0.1.1-604800000; path=/; domain=.fyers.in; HttpOnly; Secure; SameSite=None', 'server': 'cloudflare', 'cf-ray': '97d3ae09bff14829-BOM'} -+-+- b'error code: 502'","timestamp":"2025-09-11 07:49:24,663+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[__symbol_conversion:1352] data_ws","message":{"code":-300,"message":"Please provide a valid symbol","s":"error","type":"sub","invalid_symbols":["NSE:SWANENERGY-EQ"]},"timestamp":"2025-09-11 07:49:26,506+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[__symbol_conversion:1352] data_ws","message":{"code":-300,"message":"Please provide a valid symbol","s":"error","type":"sub","invalid_symbols":["NSE:SWANENERGY-EQ"]},"timestamp":"2025-09-11 09:22:12,256+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[__symbol_conversion:1352] data_ws","message":{"code":-300,"message":"Please provide a valid symbol","s":"error","type":"sub","invalid_symbols":["NSE:SWANENERGY-EQ"]},"timestamp":"2025-09-11 23:09:07,316+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[__symbol_conversion:1352] data_ws","message":{"code":-300,"message":"Please provide a valid symbol","s":"error","type":"sub","invalid_symbols":["NSE:SWANENERGY-EQ"]},"timestamp":"2025-09-12 09:21:11,361+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[__symbol_conversion:1352] data_ws","message":{"code":-300,"message":"Please provide a valid symbol","s":"error","type":"sub","invalid_symbols":["NSE:SWANENERGY-EQ"]},"timestamp":"2025-09-12 09:32:02,897+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[access_token_to_hsmtoken:272] data_ws","message":{"type":"cn","code":-99,"message":"Token is expired","s":"error"},"timestamp":"2025-09-15 09:27:03,791+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[__symbol_conversion:1352] data_ws","message":{"code":-300,"message":"Please provide a valid symbol","s":"error","type":"sub","invalid_symbols":["NSE:SWANENERGY-EQ"]},"timestamp":"2025-09-15 09:54:38,941+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[__symbol_conversion:1352] data_ws","message":{"code":-300,"message":"Please provide a valid symbol","s":"error","type":"sub","invalid_symbols":["NSE:SWANENERGY-EQ"]},"timestamp":"2025-09-16 22:00:54,861+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[__symbol_conversion:1352] data_ws","message":{"code":-300,"message":"Please provide a valid symbol","s":"error","type":"sub","invalid_symbols":["NSE:SWANENERGY-EQ"]},"timestamp":"2025-09-17 07:57:18,789+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[__symbol_conversion:1352] data_ws","message":{"code":-300,"message":"Please provide a valid symbol","s":"error","type":"sub","invalid_symbols":["NSE:SWANENERGY-EQ"]},"timestamp":"2025-09-17 09:28:23,943+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[__symbol_conversion:1352] data_ws","message":{"code":-300,"message":"Please provide a valid symbol","s":"error","type":"sub","invalid_symbols":["NSE:SWANENERGY-EQ"]},"timestamp":"2025-09-18 09:31:12,972+0530","service":"FyersDataSocket"}
{"level":"ERROR","location":"[__symbol_conversion:1352] data_ws","message":{"code":-300,"message":"Please provide a valid symbol","s":"error","type":"sub","invalid_symbols":["NSE:SWANENERGY-EQ"]},"timestamp":"2025-09-19 09:20:27,011+0530","service":"FyersDataSocket"}
